layout_spectrum: 0.1909522
typography_spectrum: 0.02949545
color:
  saturation: 0.8528683
  lightness: 0.7927998
  brandStrength: 0.697193
  rhythmicContrast: 0.02569604
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Newman ChapelHill
